# Etapa 1 — Carregamento e conhecimento do dataset

In [8]:
import pandas as pd

In [9]:
dados = pd.read_csv("/content/07_monitoramento_usina_nuclear_industrial.csv", sep = ",")

In [10]:
dados.head() #Primeiras linhas do datashet

,id_registro,data_hora,circuito,turno,status_operacional,temperatura_c,pressao_bar,vazao_m3_h,potencia_mw,radiacao_msv_h,vibracao_mm_s,nivel_refrigerante_pct,eficiencia_termica_pct,arquivo_origem,usuario_importacao
0,1,2026-02-01 00:00:00,Geracao,Tarde,Normal,89.0,20.92,6853.6,913.6,0.013,2.98,89.0,34.1,export_monitoramento_usina.dat,integracao_legado
1,2,2026-02-01 00:30:00,Geracao,Tarde,Normal,82.6,16.10,5231.0,1066.8,0.017,1.89,99.9,33.6,export_monitoramento_usina.dat,integracao_legado
2,3,2026-02-01 01:00:00,Primario,Manha,Normal,304.8,160.78,16507.5,591.3,0.035,2.42,90.6,35.5,export_monitoramento_usina.dat,integracao_legado
3,4,2026-02-01 01:30:00,Contencao,Noite,Normal,25.7,1.66,100.0,705.5,0.052,2.48,89.8,36.4,export_monitoramento_usina.dat,integracao_legado
4,5,2026-02-01 02:00:00,Contencao,TARDE,Normal,25.0,8.79,1350.7,831.9,0.044,2.42,90.3,34.0,export_monitoramento_usina.dat,integracao_legado

In [12]:
dados.shape #quantidade de linhas e colunas

(5000, 15)

In [13]:
dados.columns #nomes das colunas

Index(['id_registro', 'data_hora', 'circuito', 'turno', 'status_operacional',
       'temperatura_c', 'pressao_bar', 'vazao_m3_h', 'potencia_mw',
       'radiacao_msv_h', 'vibracao_mm_s', 'nivel_refrigerante_pct',
       'eficiencia_termica_pct', 'arquivo_origem', 'usuario_importacao'],
      dtype='object')

In [14]:
dados.dtypes #tipos de dados

id_registro                 int64
data_hora                  object
circuito                   object
turno                      object
status_operacional         object
temperatura_c             float64
pressao_bar               float64
vazao_m3_h                float64
potencia_mw               float64
radiacao_msv_h            float64
vibracao_mm_s             float64
nivel_refrigerante_pct    float64
eficiencia_termica_pct    float64
arquivo_origem             object
usuario_importacao         object
dtype: object

In [ ]:
dados.info() #infos gerais do DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_registro             5000 non-null   int64
 1   data_hora               5000 non-null   object
 2   circuito                5000 non-null   object
 3   turno                   5000 non-null   object
 4   status_operacional      4975 non-null   object
 5   temperatura_c           4975 non-null   float64
 6   pressao_bar             4975 non-null   float64
 7   vazao_m3_h              5000 non-null   float64
 8   potencia_mw             5000 non-null   float64
 9   radiacao_msv_h          5000 non-null   float64
 10  vibracao_mm_s           5000 non-null   float64
 11  nivel_refrigerante_pct  4975 non-null   float64
 12  eficiencia_termica_pct  5000 non-null   float64
 13  arquivo_origem          5000 non-null   object
 14  usuario_importacao      5000 non-null   object
dtypes: float64(8), int64(1), object(6)
memory usage: 586.1+ KB

# Etapa 2 — Tratamento de células nulas

In [15]:
dados.isna().sum() #vericando a existencia de celulas nulas

id_registro                0
data_hora                  0
circuito                   0
turno                      0
status_operacional        25
temperatura_c             25
pressao_bar               25
vazao_m3_h                 0
potencia_mw                0
radiacao_msv_h             0
vibracao_mm_s              0
nivel_refrigerante_pct    25
eficiencia_termica_pct     0
arquivo_origem             0
usuario_importacao         0
dtype: int64

In [16]:
mask1 = dados['temperatura_c'] >= 0
mediana1 = dados[mask1]['temperatura_c'].median()
dados.fillna(
    {
        'temperatura_c' : mediana1
    }, inplace=True
)

In [ ]:
dados['temperatura_c'].isna().sum()

np.int64(0)

In [17]:
dados.isna().sum()

id_registro                0
data_hora                  0
circuito                   0
turno                      0
status_operacional        25
temperatura_c              0
pressao_bar               25
vazao_m3_h                 0
potencia_mw                0
radiacao_msv_h             0
vibracao_mm_s              0
nivel_refrigerante_pct    25
eficiencia_termica_pct     0
arquivo_origem             0
usuario_importacao         0
dtype: int64

In [ ]:
dados['status_operacional'].unique()

array(['Normal', 'Alerta', 'Desligamento', nan], dtype=object)

In [ ]:
dados['status_operacional'].nunique()

3

In [ ]:
dados['status_operacional'].mode()[0]

'Normal'

In [ ]:
moda1 = dados['status_operacional'].mode()[0]
dados.fillna(
    {
        'status_operacional' : moda1
    }, inplace=True
)

In [ ]:
dados['status_operacional'].isna().sum()

np.int64(0)

In [ ]:
dados.isna().sum()

id_registro                0
data_hora                  0
circuito                   0
turno                      0
status_operacional         0
temperatura_c              0
pressao_bar               25
vazao_m3_h                 0
potencia_mw                0
radiacao_msv_h             0
vibracao_mm_s              0
nivel_refrigerante_pct    25
eficiencia_termica_pct     0
arquivo_origem             0
usuario_importacao         0
dtype: int64

In [ ]:
mask = dados['pressao_bar'] >= 0
mediana = dados[mask]['pressao_bar'].median()
dados.fillna(
    {
        'pressao_bar' : mediana
    }, inplace=True
)

In [ ]:
dados['pressao_bar'].isna().sum()

np.int64(0)

In [ ]:
dados.isna().sum()

id_registro                0
data_hora                  0
circuito                   0
turno                      0
status_operacional         0
temperatura_c              0
pressao_bar                0
vazao_m3_h                 0
potencia_mw                0
radiacao_msv_h             0
vibracao_mm_s              0
nivel_refrigerante_pct    25
eficiencia_termica_pct     0
arquivo_origem             0
usuario_importacao         0
dtype: int64

In [ ]:
mask = dados['nivel_refrigerante_pct'] >= 0
mediana = dados[mask]['nivel_refrigerante_pct'].median()
dados.fillna(
    {
        'nivel_refrigerante_pct' : mediana
    }, inplace=True
)

In [ ]:
dados['nivel_refrigerante_pct'].isna().sum()

np.int64(0)

In [ ]:
dados.isna().sum()

id_registro               0
data_hora                 0
circuito                  0
turno                     0
status_operacional        0
temperatura_c             0
pressao_bar               0
vazao_m3_h                0
potencia_mw               0
radiacao_msv_h            0
vibracao_mm_s             0
nivel_refrigerante_pct    0
eficiencia_termica_pct    0
arquivo_origem            0
usuario_importacao        0
dtype: int64

# Etapa 3 — Tratamento de valores negativos impossíveis

In [ ]:
mask = dados['pressao_bar'] < 0 #localizando os registros

In [ ]:
mask.sum()

np.int64(20)

In [ ]:
dados[mask]

,id_registro,data_hora,circuito,turno,status_operacional,temperatura_c,pressao_bar,vazao_m3_h,potencia_mw,radiacao_msv_h,vibracao_mm_s,nivel_refrigerante_pct,eficiencia_termica_pct,arquivo_origem,usuario_importacao
152,153,2026-02-04 04:00:00,Contencao,Manha,Normal,25.0,-6.90,1266.0,664.9,0.033,2.37,89.8,31.9,export_monitoramento_usina.dat,integracao_legado
800,801,2026-02-17 16:00:00,Contencao,Manha,Normal,36.6,-0.50,1393.3,734.0,0.050,3.35,88.4,35.7,export_monitoramento_usina.dat,integracao_legado
1103,1104,2026-02-23 23:30:00,Contencao,Noite,Normal,29.7,-3.09,800.5,731.0,0.030,1.87,90.6,33.9,export_monitoramento_usina.dat,integracao_legado
1517,1518,2026-03-04 14:30:00,Primario,Tarde,Normal,296.7,-152.53,17724.4,646.9,0.032,2.51,95.3,34.2,export_monitoramento_usina.dat,integracao_legado
1677,1678,2026-03-07 22:30:00,Geracao,Noite,Normal,82.5,-14.41,6736.2,926.8,0.036,2.14,82.2,34.5,export_monitoramento_usina.dat,integracao_legado
1715,1716,2026-03-08 17:30:00,Geracao,Tarde,Normal,79.7,-12.92,6156.8,955.5,0.044,1.95,95.4,33.2,export_monitoramento_usina.dat,integracao_legado
1733,1734,2026-03-09 02:30:00,Primario,Manha,Normal,303.8,-152.46,17830.8,709.8,0.042,0.30,88.1,34.0,export_monitoramento_usina.dat,integracao_legado
1812,1813,2026-03-10 18:00:00,Secundario,Tarde,Normal,240.0,-75.11,12356.5,712.1,0.037,2.90,94.0,33.8,export_monitoramento_usina.dat,integracao_legado
2150,2151,2026-03-17 19:00:00,Secundario,Manha,Normal,253.7,-66.03,14412.4,665.9,0.029,2.36,92.9,31.8,export_monitoramento_usina.dat,integracao_legado
2343,2344,2026-03-21 19:30:00,Geracao,Tarde,Normal,88.9,-14.78,7174.2,988.8,0.035,2.51,83.9,35.2,export_monitoramento_usina.dat,integracao_legado
2550,2551,2026-03-26 03:00:00,Geracao,Manha,Normal,68.9,-16.32,6154.4,916.8,0.056,0.76,91.4,34.3,export_monitoramento_usina.dat,integracao_legado
2595,2596,2026-03-27 01:30:00,Secundario,Noite,Normal,242.5,-70.22,14232.0,740.4,0.031,1.65,99.8,35.9,export_monitoramento_usina.dat,integracao_legado
3306,3307,2026-04-10 21:00:00,Contencao,Noite,Alerta,45.7,-8.22,609.5,649.5,0.069,2.59,90.8,37.1,export_monitoramento_usina.dat,integracao_legado
3848,3849,2026-04-22 04:00:00,Secundario,Noite,Normal,255.5,-70.13,14213.0,733.5,0.036,2.50,93.2,31.9,export_monitoramento_usina.dat,integracao_legado
3940,3941,2026-04-24 02:00:00,Secundario,Noite,Normal,250.5,-69.97,14920.3,647.8,0.037,2.04,91.1,35.1,export_monitoramento_usina.dat,integracao_legado
4090,4091,2026-04-27 05:00:00,Geracao,Noite,Normal,89.9,-20.89,6945.1,930.0,0.038,1.88,100.0,31.7,export_monitoramento_usina.dat,integracao_legado
4119,4120,2026-04-27 19:30:00,Contencao,Noite,Normal,37.6,-1.87,192.9,878.5,0.050,1.34,86.5,33.1,export_monitoramento_usina.dat,integracao_legado
4506,4507,2026-05-05 21:00:00,Secundario,Noite,Normal,242.3,-64.73,13920.2,790.7,0.029,0.94,94.3,36.0,export_monitoramento_usina.dat,integracao_legado
4545,4546,2026-05-06 16:30:00,Primario,Tarde,Normal,293.5,-157.21,18004.3,615.6,0.044,2.46,96.6,35.0,export_monitoramento_usina.dat,integracao_legado
4842,4843,2026-05-12 21:00:00,Contencao,Manha,Normal,25.0,-6.81,2503.0,580.6,0.046,2.14,95.7,36.3,export_monitoramento_usina.dat,integracao_legado

In [ ]:
maska = dados['pressao_bar'] >= 0
mediana = dados[maska]['pressao_bar'].median()
dados.loc[mask, 'pressao_bar'] = mediana

In [ ]:
(dados['pressao_bar'] < 0).sum()

np.int64(0)

In [ ]:
mask = dados['vazao_m3_h'] < 0
maska = dados['vazao_m3_h'] >= 0
mediana = dados[maska]['vazao_m3_h'].median()
dados.loc[mask, 'vazao_m3_h'] = mediana
(dados['vazao_m3_h'] < 0).sum()

np.int64(0)

In [ ]:
mask = dados['potencia_mw'] < 0
maska = dados['potencia_mw'] >= 0
mediana = dados[maska]['potencia_mw'].median()
dados.loc[mask, 'potencia_mw'] = mediana
(dados['potencia_mw'] < 0).sum()

np.int64(0)

# Etapa 4 — Tratamento de percentuais inválidos

In [ ]:
mask = (dados['nivel_refrigerante_pct'] > 100) | (dados['nivel_refrigerante_pct'] < 0)
dados[mask]

,id_registro,data_hora,circuito,turno,status_operacional,temperatura_c,pressao_bar,vazao_m3_h,potencia_mw,radiacao_msv_h,vibracao_mm_s,nivel_refrigerante_pct,eficiencia_termica_pct,arquivo_origem,usuario_importacao
17,18,2026-02-01 08:30:00,Secundario,Tarde,Normal,247.9,74.10,14389.0,735.7,0.037,2.73,107.6,33.7,export_monitoramento_usina.dat,integracao_legado
267,268,2026-02-06 13:30:00,Secundario,Tarde,Normal,259.6,72.75,12947.2,691.8,0.034,2.19,105.5,31.9,export_monitoramento_usina.dat,integracao_legado
436,437,2026-02-10 02:00:00,Secundario,Manha,Normal,261.4,75.71,14143.3,763.7,0.030,2.20,127.3,38.3,export_monitoramento_usina.dat,integracao_legado
665,666,2026-02-14 20:30:00,Secundario,Noite,Normal,253.0,72.06,13192.4,709.8,0.044,2.07,115.7,31.3,export_monitoramento_usina.dat,integracao_legado
1660,1661,2026-03-07 14:00:00,Primario,Noite,Normal,286.7,164.40,17389.7,760.9,0.028,1.90,129.1,35.8,export_monitoramento_usina.dat,integracao_legado
1943,1944,2026-03-13 11:30:00,Contencao,Manha,Normal,25.5,0.50,1749.4,671.3,0.056,3.18,113.2,35.6,export_monitoramento_usina.dat,integracao_legado
2638,2639,2026-03-27 23:00:00,Secundario,Noite,Normal,249.8,58.89,13687.1,680.6,0.048,1.34,102.6,38.6,export_monitoramento_usina.dat,integracao_legado
2683,2684,2026-03-28 21:30:00,Secundario,Manha,Normal,246.5,75.76,14434.1,716.4,0.041,2.48,132.9,36.4,export_monitoramento_usina.dat,integracao_legado
2759,2760,2026-03-30 11:30:00,Geracao,Tarde,Normal,91.8,21.18,3813.6,871.1,0.032,1.43,124.5,34.0,export_monitoramento_usina.dat,integracao_legado
3139,3140,2026-04-07 09:30:00,Contencao,Manha,Normal,46.0,0.50,100.0,674.2,0.032,2.32,123.3,35.3,export_monitoramento_usina.dat,integracao_legado
3293,3294,2026-04-10 14:30:00,Primario,Noite,Normal,302.2,155.04,18496.8,690.5,0.020,3.10,130.4,35.2,export_monitoramento_usina.dat,integracao_legado
3317,3318,2026-04-11 02:30:00,Primario,Manha,Normal,290.7,150.38,17485.6,745.0,0.043,1.59,105.2,31.2,export_monitoramento_usina.dat,integracao_legado
3657,3658,2026-04-18 04:30:00,Primario,Manha,Normal,300.8,155.40,17505.4,571.1,0.037,2.42,108.9,31.9,export_monitoramento_usina.dat,integracao_legado
3834,3835,2026-04-21 21:00:00,Secundario,Tarde,Normal,246.2,66.17,14745.2,566.1,0.032,2.39,124.8,36.0,export_monitoramento_usina.dat,integracao_legado
3858,3859,2026-04-22 09:00:00,Primario,Manha,Normal,298.9,161.87,16852.0,700.5,0.044,2.24,101.2,34.5,export_monitoramento_usina.dat,integracao_legado
3925,3926,2026-04-23 18:30:00,Contencao,Noite,Normal,51.0,4.98,958.0,666.4,0.052,1.55,130.8,37.2,export_monitoramento_usina.dat,integracao_legado
4060,4061,2026-04-26 14:00:00,Secundario,Manha,Normal,252.0,69.79,14413.5,684.5,0.029,1.65,134.1,35.1,export_monitoramento_usina.dat,integracao_legado
4253,4254,2026-04-30 14:30:00,Secundario,Tarde,Normal,245.0,65.97,14613.7,693.2,0.031,3.18,130.3,37.2,export_monitoramento_usina.dat,integracao_legado
4335,4336,2026-05-02 07:30:00,Contencao,Manha,Normal,41.4,1.60,118.2,566.8,0.045,1.91,103.7,37.9,export_monitoramento_usina.dat,integracao_legado
4552,4553,2026-05-06 20:00:00,Primario,Manha,Normal,285.6,158.90,17326.1,525.3,0.039,2.33,113.3,30.6,export_monitoramento_usina.dat,integracao_legado

In [ ]:
mask = (dados['nivel_refrigerante_pct'] > 100) | (dados['nivel_refrigerante_pct'] < 0)
maska = dados['nivel_refrigerante_pct'] >= 0
mediana = dados[maska]['nivel_refrigerante_pct'].median()
dados.loc[mask, 'nivel_refrigerante_pct'] = mediana

((dados['nivel_refrigerante_pct'] > 100) | (dados['nivel_refrigerante_pct'] < 0)).sum()

np.int64(0)

In [ ]:
mask = (dados['eficiencia_termica_pct'] > 100) | (dados['eficiencia_termica_pct'] < 0)
maska = dados['eficiencia_termica_pct'] >= 0
mediana = dados[maska]['eficiencia_termica_pct'].median()
dados.loc[mask, 'eficiencia_termica_pct'] = mediana

((dados['eficiencia_termica_pct'] > 100) | (dados['eficiencia_termica_pct'] < 0)).sum()

np.int64(0)

# Etapa 5 — Padronização das categorias

In [ ]:
dados['turno'].str.strip().unique()

array(['Tarde', 'Manha', 'Noite', 'TARDE', 'MANHA', 'tarde', 'NOITE',
       'noite', 'manha'], dtype=object)

In [ ]:
dados['turno'].str.strip().nunique()

9

In [ ]:
dados['turno'] = dados['turno'].str.strip()

In [ ]:
dados['turno'].unique()

array(['Tarde', 'Manha', 'Noite', 'TARDE', 'MANHA', 'tarde', 'NOITE',
       'noite', 'manha'], dtype=object)

In [ ]:
dados['turno'].value_counts()

turno
Manha    1678
Tarde    1662
Noite    1639
noite       5
manha       4
MANHA       3
TARDE       3
NOITE       3
tarde       3
Name: count, dtype: int64

In [ ]:
mapa_situacao = {
    # Operando
    'Manha' : 'Manha', # isso é para não deixar NaN, pois se o map não saber o que fazer com um dado ele deixa NaN
    'manha' : 'Manha',
    'MANHA' : 'Manha',
    # Parado
    'Tarde' : 'Tarde', # isso é para não deixar NaN, pois se o map não saber o que fazer com um dado ele deixa NaN
    'TARDE' : 'Tarde',
    'tarde' : 'Tarde',
    # Manutenção
    'Noite' : 'Noite', # isso é para não deixar NaN, pois se o map não saber o que fazer com um dado ele deixa NaN
    'noite' : 'Noite',
    'NOITE' : 'Noite'
}

In [ ]:
dados['turno'].map(mapa_situacao).isna().sum()

np.int64(0)

In [ ]:
dados['turno'] = dados['turno'].map(mapa_situacao)

In [ ]:
dados['turno'].unique()

array(['Tarde', 'Manha', 'Noite'], dtype=object)

In [ ]:
dados['circuito'] = dados['circuito'].str.strip()

In [ ]:
dados['circuito'].unique()

array(['Geracao', 'Primario', 'Contencao', 'Secundario', 'secundario',
       'CONTENCAO', 'SECUNDARIO', 'contencao', 'primario', 'PRIMARIO',
       'GERACAO'], dtype=object)

In [ ]:
dados['circuito'].value_counts()

circuito
Geracao       1260
Secundario    1256
Contencao     1246
Primario      1221
SECUNDARIO       4
contencao        4
CONTENCAO        3
PRIMARIO         2
primario         2
secundario       1
GERACAO          1
Name: count, dtype: int64

In [ ]:
mapa_situacao = {
    'Geracao' : 'Geracao', # isso é para não deixar NaN, pois se o map não saber o que fazer com um dado ele deixa NaN
    'GERACAO' : 'Geracao',

    'Secundario' : 'Secundario', # isso é para não deixar NaN, pois se o map não saber o que fazer com um dado ele deixa NaN
    'SECUNDARIO' : 'Secundario',
    'secundario' : 'Secundario',

    'Contencao' : 'Contencao', # isso é para não deixar NaN, pois se o map não saber o que fazer com um dado ele deixa NaN
    'CONTENCAO' : 'Contencao',
    'contencao' : 'Contencao',

    'Primario' : 'Primario',
    'primario' : 'Primario',
    'PRIMARIO' : 'Primario',
}

In [ ]:
dados['circuito'].map(mapa_situacao).isna().sum()

np.int64(0)

In [ ]:
dados['circuito'] = dados['circuito'].map(mapa_situacao)

In [ ]:
dados['circuito'].unique()

array(['Geracao', 'Primario', 'Contencao', 'Secundario'], dtype=object)

# Etapa 6 — Identificação e correção de inconsistências entre colunas

In [ ]:
mask = (dados['status_operacional'] == 'Normal') & (dados['radiacao_msv_h'] > 0.20)
dados.loc[mask, 'status_operacional'] = 'Desligamento'

In [ ]:
mask = (dados['status_operacional'] == 'Desligamento') & (dados['radiacao_msv_h'] > 900)
dados.loc[mask, 'potencia_mw'] = 0

# Etapa 7 — Remoção de colunas irrelevantes

In [ ]:
dados.columns
dados.drop(['arquivo_origem', 'usuario_importacao'], axis = 1, inplace=True)

# Etapa 8 — Validação do dataset tratado

In [ ]:
dados.isna().sum()

id_registro               0
data_hora                 0
circuito                  0
turno                     0
status_operacional        0
temperatura_c             0
pressao_bar               0
vazao_m3_h                0
potencia_mw               0
radiacao_msv_h            0
vibracao_mm_s             0
nivel_refrigerante_pct    0
eficiencia_termica_pct    0
dtype: int64

In [ ]:
(dados['vazao_m3_h'] < 0).sum()

np.int64(0)

In [ ]:
(dados['pressao_bar'] < 0).sum()

np.int64(0)

In [ ]:
(dados['potencia_mw'] < 0).sum()

np.int64(0)

In [ ]:
((dados['nivel_refrigerante_pct'] > 100) | (dados['nivel_refrigerante_pct'] < 0)).sum()

np.int64(0)

In [ ]:
((dados['eficiencia_termica_pct'] > 100) | (dados['eficiencia_termica_pct'] < 0)).sum()

np.int64(0)

In [ ]:
dados['circuito'].unique()

array(['Geracao', 'Primario', 'Contencao', 'Secundario'], dtype=object)

In [ ]:
dados['turno'].unique()

array(['Tarde', 'Manha', 'Noite'], dtype=object)

In [ ]:
dados.columns

Index(['id_registro', 'data_hora', 'circuito', 'turno', 'status_operacional',
       'temperatura_c', 'pressao_bar', 'vazao_m3_h', 'potencia_mw',
       'radiacao_msv_h', 'vibracao_mm_s', 'nivel_refrigerante_pct',
       'eficiencia_termica_pct'],
      dtype='object')

# Etapa 9 — Agrupamento e análise dos dados

In [ ]:
dados.groupby(['circuito', 'turno']).agg(
    Temperatura = ('temperatura_c', 'mean'),
    Potencia = ('potencia_mw', 'mean'),
    registros = ('id_registro', 'count')
)

                  Temperatura    Potencia  registros
circuito   turno
Contencao  Manha    38.771294  658.403765        425
           Noite    37.837469  664.266253        403
           Tarde    39.046353  671.959294        425
Geracao    Manha    84.731818  914.303680        462
           Noite    84.810723  913.053616        401
           Tarde    84.405528  925.052261        398
Primario   Manha   297.995771  686.980100        402
           Noite   299.095823  689.380590        407
           Tarde   299.544231  684.514183        416
Secundario Manha   249.713889  702.786616        396
           Noite   249.558945  698.452982        436
           Tarde   250.508392  697.467133        429

# Etapa 10 — Interpretação dos resultados

Com base nos resultados do agrupamento, podemos fazer as seguintes interpretações relevantes para o contexto industrial da usina nuclear:

1.  **Diferenciação Clara das Temperaturas por Circuito:** Observa-se uma variação significativa e esperada nas médias de temperatura entre os diferentes circuitos. O **Circuito Primário** opera nas temperaturas mais elevadas (aproximadamente 298-299°C), o que é consistente com ser o circuito que contém o reator e o fluido de refrigeração primário. O **Circuito Secundário** também opera em temperaturas elevadas (cerca de 250°C), indicando sua função na geração de vapor. Já o **Circuito de Geração** apresenta temperaturas moderadas (aproximadamente 84-85°C), enquanto o **Circuito de Contenção** mantém as temperaturas mais baixas (cerca de 38-39°C), refletindo sua função de segurança e isolamento. Essa distinção clara valida que os sensores estão registrando os valores esperados para cada parte do processo nuclear, sendo fundamental para o monitoramento da integridade e eficiência de cada sistema.

2.  **Concentração da Geração de Potência no Circuito de Geração:** Como esperado, o **Circuito de Geração** é o que apresenta a maior média de potência (aproximadamente 913-925 MW). Isso confirma que este é o principal circuito responsável pela produção de energia elétrica da usina. Os outros circuitos, como o Primário, Secundário e de Contenção, registram valores de potência médios significativamente menores (em torno de 658-702 MW), o que provavelmente representa o consumo interno da planta ou a potência associada a processos auxiliares, e não a geração líquida para a rede. A constância desses valores entre os turnos em cada circuito (Manhã, Tarde, Noite) sugere uma operação estável e padronizada ao longo do dia, um indicativo positivo de controle operacional e segurança.

# Etapa 11 — Exportação

In [ ]:
dados.to_csv('07_monitoramento_usina_nuclear_industrial_TRATADOS.csv', index = False)

#